"use client";
import { Navbar } from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import BackImage from "@/components/BackImage";
import Foot from "@/components/Foot/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <BackImage>
            <Navbar></Navbar>
            {children}
            <Foot></Foot>
          </BackImage>
        </Provider>
      </body>
    </html>
  );
}
